### ISSUE TITLE
Bluetooth off message, collisions, and other questions

### ISSUE THREAD

**Issue by Wado518** [davidgyoung/BackgroundAdvertiser#2]
Hi David, thanks for this app and the accompanying article (http://www.davidgyoungtech.com/2020/05/07/hacking-the-overflow-area) - it's really cool that you figured all of this out. I have a few follow-up questions:

1) When I try using the app, I see the following error:
<blockquote> [CoreBluetooth] API MISUSE: <CBPeripheralManager: 0x2801a90e0> can only accept this command while in the powered on state </blockquote>
I made sure that the app has proper bluetooth and locations permissions as explained in the readme, and that bluetooth is on, airplane mode is off, etc. Do you have any thoughts on why the app would say this is powered off?

2) I tried making my own background bluetooth communication app from scratch, with one phone set as the advertiser and one as the receiver. (I'm able to get past the issue of bluetooth being off like was happening using your app for some reason). What I'm seeing is that when at least one phone is running the app in the foreground, the advertisement gets sent/received properly. But when both are in the background, the advertisement is not detected. So it doesn't seem like either phone is having problems transmitting or receiving advertisements in the background (since both work correctly when the other is in the foreground). Have you seen this problem before? One idea I have is that because the rate with which bluetooth advertisements are sent/scanned for decreases when the app is in the background, when both are in the background, they are sending and scanning for advertisements at different times, and thee times are not aligning for there to be a connection. Does that sound reasonable?

3)  Regarding the "How iOS Handles Collisions" section in your article. You mention that 
<blockquote> iOS will give a scanning callback for the colliding but different service UUID </blockquote>

How do I as a programmer access this callback/define the behavior for when there's a collision? What I am seeing is that if I broadcast an advertisement in the background with a few service UUIDs, where some are from your Overflow Service UUIDs by Bit Position table and some are chosen arbitrarily (not from that table), the list of service UUIDs in the advertisement received includes all of the ones from your table, but the arbitrarily chosen UUIDs are converted into different UUIDs. So it seems like the ones not from your table are being changed to other UUIDs which correspond to the same bit positions. But how do I know that it's a different UUID than what was originally advertised (since there was a "collision")? Though it would make sense to me if it's impossible to make the distinction- it's not like there's some data in the advertisement indicating that there was a collision right? So if you could just explain the "How iOS Handles Collisions" section of the article a bit more I'd really appreciate it.

**Comment by davidgyoung** [comment]
Hi, @Wado518.

Regarding these points:

1. The error is probably caused by a timing issue where either the
transmitter or the scanner is started prematurely before CoreBluetooth
transitions to an on state.  Some subtle OS change since I last tested this on iOS 15 may be causing that.  I will need to reproduce and find the timing fix.  But you may find that bringing the app to the background, then the foreground, and finally the background again may fix this.


2.  For this to work and for advertisements to be detected, the screen must
be on with the receiving device.  That is why the sample sends screen on
notifications to temporarily illuminate the screen.  Make sure you are
doing this.

3. You simply cannot distinguish collisions in the advertisement pattern.
The  hash algorithm from service uuid set  to overflow area bitmask is a
one way hash that destroys information.   The sample app accepts this
limitation and still works in most cases by using a Hamming error
correction code that provides one bit error correction — meaning that at
most one other app on the phone may be advertising a service and setting an
unexpected bit in the overflow area and this will still work.  You can see
this in the line here:

https://github.com/davidgyoung/OverflowAreaBeaconRef/blob/master/OverflowAreaBeaconRef/OverflowArea/BackgroundBeaconManager.swift#L85

**Comment by davidgyoung** [comment]
Upon further investigation I can confirm this app still works on iOS 16.0. Detections are made in the foreground and background (whenever the screen comes on due to the app's periodic notifications or regular user activity).

The warning line is benign and happens if you try to start transmitting before the Bluetooth powered on event. 

`[CoreBluetooth] API MISUSE: can only accept this command while in the powered on state`

But the app is designed to correct for this later by restarting transmission after this event.  I have modified the debug lines emitted by the app to make this less misleading:


```
2023-01-16 09:49:29.157593-0500 OverflowAreaBeaconRef[7655:1757837] Cannot start transmitting with bluetooth powered off.  We will retry when we receive the power on event.
...
2023-01-16 09:49:29.273463-0500 OverflowAreaBeaconRef[7655:1757837] Bluetooth powered on event received
...
2023-01-16 09:49:29.381850-0500 OverflowAreaBeaconRef[7655:1757837] Starting transmitting
```
